# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://erlebnis-film.at
title: Erlebnis Film
email: info@erlebnis-film.at
author: Your Name
description: > # "Write an awesome description for your new site here. 
  Das einzigarte Filmerlebnis!
copyright: 'Copyright &copy; 2024 by David Reinisch. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url: 
